inherit_from:
  - .rubocop-airbnb.yml

Rails:
  Enabled: true

LineLength:
  Max: 200

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
    - '**/Gemfile'
    - 'vendor/**/*'
    - '.git/**/*'
    - 'frontend/**/*'
